server:
  port: 8082

spring:
  application:
    name: logoffservice

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka_uri:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

microservices:
  databaseService:
    session: http://databaseservice/domain/user/session
    loginDetails: http://databaseservice/domain/user/updateLoginDetails
