version: '2.1'
services:
  db:
    image: "postgres"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=greg
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - node.name=es
      - cluster.name=es-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    depends_on:
      - db
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 5s
        timeout: 1s
        retries: 20
  be:
    build: ./userservice
    container_name: be
    depends_on:
      es:
        condition: service_healthy
    ports:
      - 8080:8080
  fe:
    build: ./user-app
    container_name: fe
    depends_on:
      - be
    ports:
      - 4200:80
